---
abstract: 'Does your POE process have access to the web'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.42
  Test::NoWarnings: 1.00
  Test::POE::Stopping: 1.07
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: POE::Declare::HTTP::Online
name: POE-Declare-HTTP-Online
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  POE::Declare: 0.54
  POE::Declare::HTTP::Client: 0.04
  Params::Util: 1.00
  perl: 5.8.0
resources:
  ChangeLog: http://fisheye2.atlassian.com/changelog/cpan/trunk/POE-Declare-HTTP-Online
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/POE-Declare-HTTP-Online
version: 0.01
